# Generated by Django 3.2.9 on 2023-04-17 17:42

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False, verbose_name='File ID')),
                ('upload_file', models.FileField(blank=True, null=True, storage=upload.models.OverwriteStorage(), upload_to=upload.models.file_directory_path_instance, verbose_name='Upload File')),
                ('upload_time', models.DateTimeField(auto_now=True, verbose_name='Upload Time')),
            ],
        ),
    ]
